namespace PigeonCorp.Research
{
    public enum BonusType
    {
        BUY_BUTTON_RATE_MULTIPLIER,
        EGG_VALUE_MULTIPLIER,
        EGG_LAYING_RATE_MULTIPLIER,
        HATCHERY_CAPACITY_INCREMENT,
        VEHICLE_SHIPPING_RATE_INCREMENT,
        RESEARCH_DISCOUNT,
        HATCHERY_DISCOUNT,
        VEHICLE_DISCOUNT,
        PIGEON_DISCOUNT
    }
}